name: Python package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  python_package_name: nessus-file-analyzer
  folder_package_name: nessus_file_analyzer

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tools
        run: |
          python -m pip install --upgrade pip build setuptools wheel twine
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Install locally
        run: |
          ls
          ls dist
          TOOL_CURRENT_VERSION=`sed -e 's/.*__version__ = "\(.*\)".*/\1/' ${{ env.folder_package_name }}/_version.py`
          pip install dist/${{ env.folder_package_name }}-${TOOL_CURRENT_VERSION}-py3-none-any.whl
        shell: bash
      - name: pip show package
        run: |
          pip show ${{ env.python_package_name }}